# Generated by Django 3.0.3 on 2020-04-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=False, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
